### ISSUE TITLE
下载音频文件时报错

### ISSUE THREAD

**Issue by yaowu1st** [dotennin/baidu-pan-downloader#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yaowu1st** [comment]
下mp3,flac,m4a等文件时出现Error: not_whitelisted

**Comment by tvcat** [comment]
@yaowu1st 
check this out, #8

**Comment by yaowu1st** [comment]
@tvcat Thank you for your help!
