### ISSUE TITLE
插件自动下载后的文件存在哪里呀

### ISSUE THREAD

**Issue by xinmokunshou** [dotennin/baidu-pan-downloader#12]
**Is your feature request related to a problem? Please describe.**
插件自动下载完成后，会跳出选项框，选择保存的地点，那么下载过程中的文件是存在temp中了吗？
不小心关掉跳出的保存位置选项后，无法再次进入。只得再次下载。

**Describe the solution you'd like**
希望添加一个比较明显的选项，可以再度进入保存选项框。

**Comment by dotennin** [comment]
> 插件自动下载完成后，会跳出选项框，选择保存的地点，那么下载过程中的文件是存在temp中了吗？
> 不小心关掉跳出的保存位置选项后，无法再次进入。只得再次下载。

下载过程中的文件不会存在TEMP中， 而是在RAM中。 所以一旦关闭了页面后就不能再次下载。
浏览器级别无法存储大信息的临时文件。

> 希望添加一个比较明显的选项，可以再度进入保存选项框。

主流内核的浏览器现在连关闭页面弹出警告的信息都不能自定义了。 要实现此功能只能是APP级别了。

**Comment by xinmokunshou** [comment]
> > 插件自动下载完成后，会跳出选项框，选择保存的地点，那么下载过程中的文件是存在temp中了吗？
> > 不小心关掉跳出的保存位置选项后，无法再次进入。只得再次下载。
> 
> 下载过程中的文件不会存在TEMP中， 而是在RAM中。 所以一旦关闭了页面后就不能再次下载。
> 浏览器级别无法存储大信息的临时文件。
> 
> > 希望添加一个比较明显的选项，可以再度进入保存选项框。
> 
> 主流内核的浏览器现在连关闭页面弹出警告的信息都不能自定义了。 要实现此功能只能是APP级别了。

好的。感谢开发插件。我这边设置了关闭自动下载，用直链配合idm下载了。
