### ISSUE TITLE
Download big size file stuck at 100% 

### ISSUE THREAD

**Issue by vault101** [dotennin/baidu-pan-downloader#13]
**Describe the bug**
Download big size file stuck at 100% 

**To Reproduce**
1. Set "Don't ask for download save folder" in Edge
2. Go to pan.baidu.com/disk/home, check a file with size 40M (or much smaller), click "+" to download. After 100%, Windows 10 prompts notification from Edge, and browser auto save the file
3. Go to pan.baidu.com/disk/home, check a file 500M (or bigger), click "+" to download. After 100%, no Windows 10 notification, browser not saving the file, the progress stops at 100%
4. Changing the script option "auto download" or  Edge option "Don't ask for download save folder"  didn't fix the issue

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge 
 - Version 版本 85.0.564.44 (官方内部版本) (64 位)
Extension: Chrome store Violentmonkey
Installed dist/bundle.user.js

**Comment by dotennin** [comment]
Cannot reproduced follow the same steps in my local env. 
Guess rejected by your firewall? 🤔 

* Windows 10
* Microsoft Edge Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44
* Tampermonkey v4.10.6111 by Jan Biniok
* baidu-pan-downloader version 3.3.1

**Comment by vault101** [comment]
Not sure about this, change to Google Chrome Version 85.0.4183.83 (Official Build) (64-bit) + Tampermonkey fix the issue. Need more tests to cross check.
