### ISSUE TITLE
Problem during build step of installation

### ISSUE THREAD

**Issue by kadirbeytorun** [dotennin/baidu-pan-downloader#15]
When I run npm run build after successfull npm install, this is what I get as error, do you know why this could be happening?

>npm run-script build
> baidu-pan-downloader@3.3.1 build /home/kadir/Documents/baidu-pan-downloader
> npm run clean && react-app-rewired build && node user-script.js > ./dist/bundle.user.js && cat ./build/static/js/main.js >> ./dist/bundle.user.js
> baidu-pan-downloader@3.3.1 clean /home/kadir/Documents/baidu-pan-downloader
> rimraf build/*
>/home/kadir/Documents/baidu-pan-downloader/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:30
>		} catch {}
>		        ^
>SyntaxError: Unexpected token {
>    at createScript (vm.js:80:10)
>    at Object.runInThisContext (vm.js:139:10)
>    at Module._compile (module.js:616:28)
>    at Object.Module._extensions..js (module.js:663:10)
>    at Module.load (module.js:565:32)
>    at tryModuleLoad (module.js:505:12)
>    at Function.Module._load (module.js:497:3)
>    at Module.require (module.js:596:17)
>    at require (internal/module.js:11:18)
>    at Object.<anonymous> (/home/kadir/Documents/baidu-pan-downloader/node_modules/terser-webpack-plugin/dist/index.js:26:38)
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! baidu-pan-downloader@3.3.1 build: `npm run clean && react-app-rewired build && node user-script.js > ./dist/bundle.user.js && cat ./build/static/js/main.js >> ./dist/bundle.user.js`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the baidu-pan-downloader@3.3.1 build script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dotennin** [comment]
This issue has not been processed for a long time. hence close it.
