### ISSUE TITLE
Doesn't always work with the latest version of IDM & Microsoft Edge

### ISSUE THREAD

**Issue by mikhaelcool7** [dotennin/baidu-pan-downloader#16]
**Describe the bug**
Recently I am no longer able to download from Baidu Cloud Storage. Used to work flawlessly without any issues and today I was able to download one file by using a small workaround. The link in "Local Chain/本地直链" didn't appear like usually when I select a file I need and decided to select the file again and press Download directly in the Baidu Cloud Storage to let it generate a link and that actually fixed it and a direct download link in "Local Chain/本地直链" appeared. Used IDM and the file downloaded successfully. Tried to replicate the workaround to download another file but it didn't work and no matter if I clear all my cookies in my browser and login again, nothing has fixed the issue and I am no longer able to download from Baidu. Downloading fails after some time in the script menu too. EDIT: After trying several times for hours, it started to download the second file. Could have been an extension conflict.

**To Reproduce**
 - Simply try to use the script as usual with Tampermonkey and you will not be able to download directly with IDM

**Expected behavior**
 - After selecting a file, a link should appear in "Local Chain/本地直链" and successfully download with IDM

**Screenshot**
![Screenshot (20)](https://user-images.githubusercontent.com/5103276/101625310-82ec8a00-3a1b-11eb-873c-3e27dd84333f.png)
![Screenshot (21)](https://user-images.githubusercontent.com/5103276/101625468-bc24fa00-3a1b-11eb-8228-97c15aef04ad.png)
![Screenshot (22)](https://user-images.githubusercontent.com/5103276/101628066-8e41b480-3a1f-11eb-8592-ea3706f10bfd.png)

**Desktop**
 - OS: [Windows 10 Home 20H2]
 - Browser: [Microsoft Edge Version 87.0.664.57 - Official build - 64-bit]
 - Downloader: [Internet Download Manager Version 6.38 Build 14]

**Comment by dotennin** [comment]
Local chain are no longer used for now (not working properly), I have now changed to share link download mode. (which are a little faster than local chain but still very slow Orz
