### ISSUE TITLE
pan.baidu.com/s/ url

### ISSUE THREAD

**Issue by giturfreakon** [dotennin/baidu-pan-downloader#2]
Please add support for pan.baidu.com/s/ links. Xiexie.

**Comment by ShaderFallback** [comment]
自己添加下就可以了   脚本编辑 > 包括排除 > 用户包括 > 添加 >https://pan.baidu.com/s/*   保存即可
(感谢作者的脚本~)

**Comment by dotennin** [comment]
已经添加
