### ISSUE TITLE
Use the `baidu-pan-downloader` with development and dynamic loading mode in `Tampermonkey`.

### ISSUE THREAD

**Issue by hongyi-zhao** [dotennin/baidu-pan-downloader#34]
On Ubuntu 20.04.3 LTS, I want to directly use the `baidu-pan-downloader` in development and dynamic loading mode without the help of Greasemonkey. The detailed steps are as follows:

```
$ node --version
v16.10.0
$ git clone https://github.com/dotennin/baidu-pan-downloader.git baidu-pan-downloader.git 
$ cd baidu-pan-downloader.git 
$ npm install
$ npm run build
#https://stackoverflow.com/questions/51706882/create-react-app-how-do-i-npm-start-with-a-specific-browser
# If available, the Chrome browser will be used first.
# To use a different, use the following environment variable setting:
$ BROWSER=firefox npm start
```
Through the above method, the Firefox browser will automatically open and navigate to https://pan.baidu.com/disk/home. But I'm still not sure whether the above method will let me directly use the `baidu-pan-downloader` in development and dynamic loading mode without the help of Greasemonkey.

Any hints/comments/explanations will be highly appreciated.

Regards,
HZ

**Comment by dotennin** [comment]
copy/install [react-userscripts-dev.user.js](https://github.com/dotennin/baidu-pan-downloader/blob/master/dist/react-userscripts-dev.user.js) to your Greasemonkey . 

it will load the source from the port 5000 on your local. 
BTW HMR function is not supported for now.

**Comment by hongyi-zhao** [comment]
An additional question first: At the build step of `baidu-pan-downloader`, I noticed the following message, but wasn't sure if it was harmful:
```
$ npm run build
[...]
Creating an optimized production build...
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.6.0

YOUR TYPESCRIPT VERSION: 3.9.6

Please only submit bug reports when using the officially supported version.

=============
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Compiled with warnings.

./src/components/Button.tsx
  Line 9:5:    The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 11:12:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  97.45 KB  build/static/js/main.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy
```

> copy/install [react-userscripts-dev.user.js](https://github.com/dotennin/baidu-pan-downloader/blob/master/dist/react-userscripts-dev.user.js) to your Greasemonkey.

I am not familiar with `Greasemonkey`, so I describe the steps as follows. If I am wrong, please correct me at any time:

1. Start [a supported browser](https://github.com/dotennin/baidu-pan-downloader#-browser-support), say, Firefox as follows

```
$ BROWSER=firefox npm start
```
Then install the `Greasemonkey` add-on and paste the [react-userscripts-dev.user.js](https://github.com/dotennin/baidu-pan-downloader/blob/master/dist/react-userscripts-dev.user.js) as a script and save it, as shown below:

![image](https://user-images.githubusercontent.com/11155854/148521025-955cbd00-22d7-4320-a42f-95f194235478.png)

Then log in to my Baidu network disk as follows:

![image](https://user-images.githubusercontent.com/11155854/148523255-40a50c9c-a1dc-4766-a91e-1ffa60b57089.png)

But I still can't find the logo of `baidu-pan-downloader`, so don't know how to use it.

OTOH, even I don't use `baidu-pan-downloader`, I still can download the files from browser, as follows:

![image](https://user-images.githubusercontent.com/11155854/148524042-e64767ed-1b56-447a-9216-ea219964e01c.png)

As you can see, I can download files from Baidu network disk without the help of `baidu-pan-downloader`, so why must I install it?

> BTW HMR function is not supported for now.

What's HMR function and its role?

**Comment by dotennin** [comment]
Some small files like .pdf .txt can be downloaded directly from the web side without any plugins or baidu client.
But looks like `baidu-pan-downloader` does not run successfully on your local. 
> What's HMR function and its role?
it's [Hot module replacement] exchanges, adds, or removes modules while an application is running, without a full reload for the development.

**Comment by hongyi-zhao** [comment]
> Currently I dun't know the availability of Greasemonkey please use Tampermonkey instead

See following, but it seems that `baidu-pan-downloader` still does not run successfully on my machine:

![image](https://user-images.githubusercontent.com/11155854/148635096-b345f588-b38b-48bf-b924-6ec6ddab3869.png)
![image](https://user-images.githubusercontent.com/11155854/148635128-2dd4ed12-811d-42cc-ac03-041a74ed3afe.png)

**Comment by dotennin** [comment]
@hongyi-zhao  Did you run `npm start` ? does it show any information ?

**Comment by hongyi-zhao** [comment]
The Firefox shown above is opened automatically by the following command at the root directory of locally cloned `baidu-pan-downloader` repository:

```
werner@X10DAi-00:~/Public/repo/github.com/dotennin/baidu-pan-downloader.git$ BROWSER=firefox npm start
```
After the above command started, the terminal console will stay in place of the information shown below:

![image](https://user-images.githubusercontent.com/11155854/148635579-028c5ebb-5f47-45c1-892c-860dbdb7f39a.png)

And I can also confirm the port 5000 is up:

```
$ lsof -i :5000
COMMAND     PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    3341223 werner   23u  IPv4 5364946      0t0  TCP *:5000 (LISTEN)
```

**Comment by dotennin** [comment]
@hongyi-zhao  it's working for me.
 does the console show any errors on your Firefox ?

**Comment by hongyi-zhao** [comment]
See the following:
```
$ npm start &> ~/log
$ cat ~/log

> baidu-pan-downloader@3.3.1 start
> react-app-rewired start

ℹ ｢wds｣: Project is running at http://192.168.10.100/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /home/werner/Public/repo/github.com/dotennin/baidu-pan-downloader.git/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Files successfully emitted, waiting for typecheck results...
Compiled with warnings.

./src/components/Button.tsx
  Line 9:5:    The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 11:12:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

**Comment by dotennin** [comment]
@hongyi-zhao  I mean the browser console(developer tool)

**Comment by hongyi-zhao** [comment]
![image](https://user-images.githubusercontent.com/11155854/148637417-60500d17-29a8-4386-8d4d-972a27d55a9b.png)

**Comment by dotennin** [comment]
`Userscript: Dev mode started` should need to be displayed on your console. dun't know 
![image](https://user-images.githubusercontent.com/18552970/148638487-f0a6f3d4-27f1-4abd-bf76-5314c5d0748a.png)
![image](https://user-images.githubusercontent.com/18552970/148638513-4f130f17-69d9-4286-9ac3-a3594adca1dc.png)

**Comment by hongyi-zhao** [comment]
Now, it seems to actually work, but the speed is choppy:

![image](https://user-images.githubusercontent.com/11155854/148638816-289ee748-fa14-40a9-b1b7-cea21beff325.png)

What I observed is that suddenly there will be a very high speed, and then it will change to 0 speed, and go back and forth in turn. So I think it has been detected by Baidu and blocked.

BTW: What screen capture tool do you use to get the screenshots posted above?

**Comment by dotennin** [comment]
Yeah , that's why I hardly update this plugin any more. the speed has been limited. 
 Now I have already changed to the share download mode. more or less the will be better although. 
But still no idea to avoid the limitation from baidu cloud 😞 

> BTW: What screen capture tool do you use to get the screenshots posted above?
[snipaste](https://www.snipaste.com/), it's a free software , but doens't sesm to be open source

**Comment by dotennin** [comment]
>  OTOH, for a pdf file, though it can be downloaded rapidly by baidu-pan-downloader, but the result is compressed in a zip archive, which includes so many image files, such as tiff, jpeg, and so on, as shown below:

Yeah , some files with the suffix like `.pdf .exe` cannot be downloaded directly, and need to be renamed before . 
That's why it does shows as `. __________ rename me.zip` suffix,  please delete it

**Comment by hongyi-zhao** [comment]
> Now I have already changed to the share download mode.

The previous version already supplied two modes: locally direct connect and share download mode. So I don't know what do you mean by saying the above.

> [snipaste](https://www.snipaste.com/), it's a free software

There is currently no Linux version of this tool, which makes it useless for me.

> That's why it does shows as `. __________ rename me.zip` suffix, please delete it

Thank you. The following does the trick:

`$ mv something.pdf. __________ rename me.zip something.pdf`

To summarize: In any case, any cloud storage is under the control of the provider itself. It seems meaningless to further study the technology behind this tool, which will only cause a waste of time.

**Comment by dotennin** [comment]
> I don't know what do you mean by saying the above. More specifically, the previous version already supplied two modes: locally direct connect and share download mode as shown below, denoted by 1 and 2:

the default download mode was locally direct and I switched to share download mode for now
-----------------

> To summarize: In any case, any cloud storage is under the control of the provider itself. It seems meaningless to further study the technology behind this tool, which will only cause a waste of time. Further speaking, any further research and experimentation with other similar tools is not necessary too.
Yeah , agreed. To be honest , the only use of this plugin at this stage is to download smaller files that are (usually less than 200MB or smaller size) directly. without additional baidu client or the third-party downloader.

I can provide a SVIP tokens to unlimit the speed. but this is not a long term soution.

**Comment by hongyi-zhao** [comment]
> I can provide a SVIP tokens to unlimit the speed.

If you do, I think you've already paid Baidu. If so, no matter what download method you use, the speed limit should already be unlocked. So what's the point of using this tool?

**Comment by dotennin** [comment]
it can be used to provide unlimited link to multi users.

**Comment by hongyi-zhao** [comment]
In principle, this is not a technology-based cracking, but a commercial service supplied by its provider. Such things should not be the core focus of such tools: It means compromise for commercial services and failure to break through technical barriers.

**Comment by tvcat** [comment]
> 

Baidu force the free user to install their client to download big file. This tool bypass that.

**Comment by hongyi-zhao** [comment]
It has been invalidated/blocked by Baidu currently.

**Comment by tvcat** [comment]
Just tested, it still work. You need to add the file to your drive first.

**Comment by hongyi-zhao** [comment]
What do you mean by saying `add the file to your drive`? Do you have more detailed instructions on your exact steps?

**Comment by tvcat** [comment]
You need a Baidu Pan account. Add the shared file to your Baidu Pan then download using this tool.

**Comment by hongyi-zhao** [comment]
Strange. All my testings described here in this issue are done this way.

**Comment by tvcat** [comment]
Can you see the "+" icon at the bottom right in Baidu Pan website?

**Comment by hongyi-zhao** [comment]
Yes. There is a `+` sign resided in a red circle in the bottom right corner of the screen. When I click on an item I want to download, then click the `+` sign, `baidu-pan-downloader`. But I've only observed stuttering downloads, almost constant pauses, making it impossible for me to use the tool at all.

**Comment by tvcat** [comment]
So the tool did show the download speed? Is the download percentage go forward?
The file I test download is over 40% now for a 200MB++ file, It is expected for a free user.

**Comment by hongyi-zhao** [comment]
Could you please give a screenshot?

**Comment by tvcat** [comment]
![Screenshot 2022-01-10 at 16-54-45 百度网盘-全部文件](https://user-images.githubusercontent.com/119237/148739782-200f2302-3fd2-4d7d-819a-a4a675a45866.png)

**Comment by hongyi-zhao** [comment]
OK. See the following testing result on my machine with Firefox using the following script installed into tampermonkey:
```
$ curl -O https://raw.githubusercontent.com/dotennin/baidu-pan-downloader/master/dist/bundle.user.js -x socks5://127.0.0.1:18888
```

![image](https://user-images.githubusercontent.com/11155854/148740929-900e1909-294e-4708-a71a-4fabda9c6ac1.png)

![image](https://user-images.githubusercontent.com/11155854/148741204-3a6cc384-e23b-4bad-b5e5-466ada004f20.png)

And as you can see, I've logged in with my Baidu SVIP account privilege:

![image](https://user-images.githubusercontent.com/11155854/148741663-7d7760ad-e218-4a5b-8eb6-71479b2c739b.png)

**Comment by tvcat** [comment]
Firefox has a built in screenshot tool, just right click and select `Take Screenshot`.

As mentioned by @dotennin, you will need to pull the one on Aug 31, 2020 or before to use the local direct download. I do not have SVIP so I cannot test this.

To do it, close the Baidu Pan website and click the link below, Tampermonkey should run. Click reinstall then open Baidu Pan website, now the local direct download button should work.

https://github.com/dotennin/baidu-pan-downloader/raw/b4f3f7dc8afda8b11b93b7e426f4611ade73df96/dist/bundle.user.js

**Comment by hongyi-zhao** [comment]
I tried with it, but still observed an intermittent download speed:

![image](https://user-images.githubusercontent.com/11155854/148767002-5733d47c-b698-4018-be68-c14a75f62243.png)

![image](https://user-images.githubusercontent.com/11155854/148767032-87680411-0272-40c6-9138-316c79da4f0e.png)

**Comment by tvcat** [comment]
Can you see the generated link when you click the local direct download button?

**Comment by hongyi-zhao** [comment]
Nothing:

![image](https://user-images.githubusercontent.com/11155854/148862434-39d112ea-c82d-4f99-b327-2a4619f94dd9.png)

**Comment by tvcat** [comment]
Try the latest update. There is a new option to change the download mode. Try both. Remember to refresh the Baidu Pan website after changing setting and before download.

I can't help further if it still not working as I do not have a SVIP account.

**Comment by hongyi-zhao** [comment]
Yes, I've tried the project’s latest Git master commit, but unfortunately, they all ran into the same problem. Anyway, I'm using the baidunetdisk with my SVIP account currently. Otherwise, it is a waste of resources: Isn't this a failure to live up to official expectations.

**Comment by tvcat** [comment]
It is still very usable for free account user to bypass the desktop client. This is a very hard thing to do as Baidu will keep changing to kill off this kind of bypass as this reduce their profit.

It is too harsh to call this a failure.

**Comment by hongyi-zhao** [comment]
> Maybe you can try Wine and install the Windows desktop client of Baidu Pan.

As you can see, I'm using baidunetdisk installed by [baidunetdisk_3.5.0_amd64.deb](https://issuecdn.baidupcs.com/issue/netdisk/LinuxGuanjia/3.5.0/baidunetdisk_3.5.0_amd64.deb), do you mean this is the counterpart of the Windows desktop client of Baidu Pan for Windows?

**Comment by tvcat** [comment]
Didn't know they has a Linux version. The latest is 4.3.0, maybe that fixed the crash issue.
or you can download the Windows client and install with Wine.

https://pan.baidu.com/download

**Comment by hongyi-zhao** [comment]
> The latest is 4.3.0, maybe that fixed the crash issue.

The [baidunetdisk_4.3.0_amd64.deb](https://issuepcdn.baidupcs.com/issue/netdisk/LinuxGuanjia/4.3.0/baidunetdisk_4.3.0_amd64.deb) still crashes based on my tries on Ubuntu 20.04.3 LTS, but [baidunetdisk_3.5.0_amd64.deb](https://issuecdn.baidupcs.com/issue/netdisk/LinuxGuanjia/3.5.0/baidunetdisk_3.5.0_amd64.deb) works well.

> https://pan.baidu.com/download

The Linux version is already listed on this official download site.
