### ISSUE TITLE
yong bu liao~help~

### ISSUE THREAD

**Issue by nijunnijun** [dotennin/baidu-pan-downloader#4]
Hi OP, I try to download some files from my pan.baidu.com/disk/ but the download progress is stuck at 0% and no download speed is given. I just ran it in Chrome with tampermonkey add-in. Do I do anything wrong here? Thanks!!!!!

**Comment by dotennin** [comment]
Can you provide the browser version ？
Afaik,  It's always stop at 0% without any progress on Firefox

**Comment by 1033588785** [comment]
我想知道下载的文件在哪……

**Comment by nijunnijun** [comment]
> Can you provide the browser version ？
> Afaik, It's always stop at 0% without any progress on Firefox
It's Chrome version 83.0.4103.116(Official Build) 64bit. It should be the latest version I guess.....

**Comment by shanke0303** [comment]
是不是被和谐了 进度都是error

**Comment by dotennin** [comment]
> > Can you provide the browser version ？
> > Afaik, It's always stop at 0% without any progress on Firefox
> > It's Chrome version 83.0.4103.116(Official Build) 64bit. It should be the latest version I guess.....

Thanks for sharing. 
BTW, can you plz upgrade to the latest tampermonkey version that may reslove this problem

**Comment by dotennin** [comment]
> 是不是被和谐了 进度都是error

估计被暂时性黑名单了， 尝试清除网盘cookie，重新登录。 
或者换个账号

**Comment by dotennin** [comment]
> 我想知道下载的文件在哪……

下载文件完成后会提示用户储存，完成之前会以Blob形式在内存中

**Comment by lychichem** [comment]
> > 我想知道下载的文件在哪……
> 
> 下载文件完成后会提示用户储存，完成之前会以Blob形式在内存中

以blob形式在内存中，如果下载的文件大小超出用户物理内存的大小不就爆内存了……有没有计划加入个下载xxGB（MB）后自动保存部分的功能……

**Comment by dotennin** [comment]
> > > 我想知道下载的文件在哪……
> > 
> > 
> > 下载文件完成后会提示用户储存，完成之前会以Blob形式在内存中
> 
> 以blob形式在内存中，如果下载的文件大小超出用户物理内存的大小不就爆内存了……有没有计划加入个下载xxGB（MB）后自动保存部分的功能……

插件不具备硬盘读写的存限， 这个功能需要APP级别才能实现。
