### ISSUE TITLE
100%以后下载文件全是1k大小,打开里面内容如下

### ISSUE THREAD

**Issue by truecsj** [dotennin/baidu-pan-downloader#6]
chrome浏览器,版本号 77.0.3865.90
100%以后下载文件全是1k大小,打开里面内容如下
{"redo":2,"error_code":31626,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":4295073190928875781}

**Comment by tvcat** [comment]
Did you login before download?

**Comment by dotennin** [comment]
尝试重新登录试一试

**Comment by truecsj** [comment]
重新登录了,还是一样.
我发现每次会先下载一个1k文件,然后下载开始,等100%以后,速度降为0k,然后没有任何反应,1k文件还在那里,不会重新弹出浏览器下载
感觉后面整个下载过程是正常的,但没有最后一步合并文件,弹出下载

**Comment by tvcat** [comment]
@truecsj 
If the file is too big then you need to add the file to your disk then download from there.
Please post the link to that file if you are ok with it.

**Comment by truecsj** [comment]
@tvcat 
我都是加到自己网盘里然后下载的,文件大的小的我都试过
都不行
今天测试结果:进度可以往前走,但是100%后不会弹出下载

**Comment by tvcat** [comment]
@truecsj It will not pop up by default, check the default download folder, the file will be  there after 100%.

**Comment by dotennin** [comment]
@truecsj 


##关于默认下载位置，以Chrome为例
1. 打开设置页面：`chrome://settings/?search=下载`
2. 修改图中的设置项即可

 <img src="https://greasyfork.org/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZG89IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b28afb4aac736c362a53ef9e93835e4ee8df033b/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20200703160219.jpg?locale=zh-CN" width="50%">

## 如果出现无法下载的情况时的处理方式:
- 删除cookie重新登录
