### ISSUE TITLE
7z文件无法下载

### ISSUE THREAD

**Issue by kkzhh** [dotennin/baidu-pan-downloader#8]
7z文件无法下载，但只要把7z的文件扩展名删除后就能正常下载了

浏览器是 Edge  84.0.522.28 (官方内部版本) beta (64 位)

**Comment by tvcat** [comment]
Are you using Tampermonkey? 7z is not in the whitelist of Tampermonkey settings.
Try adding 7z to the whitelist in the Tampermonkey settings.

**Comment by kkzhh** [comment]
Thank you for your help, but how do I adding 7z to the whitelist in the Tampermonkey settings? Sorry i don't know much about these

**Comment by tvcat** [comment]
1. Go to the `Dashboard` of Tampermonkey.
2. Change `Config mode` to `Beginner`
3. Scroll to the bottom then you will see the `Download Beta`.
4. Put `.7z` in a new line in the whitelist box then `Save` and try it.

**Comment by kkzhh** [comment]
It finally works fine. Thanks for your help solving this problem.

**Comment by dotennin** [comment]
> 1. Go to the `Dashboard` of Tampermonkey.
> 2. Change `Config mode` to `Beginner`
> 3. Scroll to the bottom then you will see the `Download Beta`.
> 4. Put `.7z` in a new line in the whitelist box then `Save` and try it.

Already updated source  and It has been automatically renamed for `7z` (may not be friendly to some users who use the settings in above tvcat said ) 🤔
